title: mimx
description: Notes on IAM, identity architecture, and real-world access problems.
author: Mohamed Yehia
baseurl: ""
url: "https://mimx.github.io"
permalink: /posts/:slug/
markdown: kramdown
highlighter: rouge
theme: null
plugins:
  - jekyll-feed
